const resList = [
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "93262",
            name: "Hotel Maa",
            uuid: "bcc523ad-00c7-438d-84d6-966b356c8179",
            city: "14",
            area: "Race Course",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "eeqwsj031qwrklkzt4bw",
            cuisines: [
                "South Indian",
                "Indian",
                "Beverages",
                "Ice Cream",
                "Chinese",
            ],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 28,
            minDeliveryTime: 28,
            maxDeliveryTime: 28,
            slaString: "28 MINS",
            lastMileTravel: 4.300000190734863,
            slugs: {
                restaurant: "hotel-maa-anna-statue-dummy-inbound-area",
                city: "coimbatore",
            },
            cityState: "14",
            address: "Anna Statue",
            locality: "Avinashi Road",
            parentId: 9101,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 2900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 2900,
                message: "",
                title: "Delivery Charge",
                amount: "2900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=6965466~p=1~eid=00000188-c901-79a5-0ed3-63e500d30169",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "4.3 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹100 OFF",
                subHeader: "ABOVE ₹399",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "93262",
                deliveryTime: 28,
                minDeliveryTime: 28,
                maxDeliveryTime: 28,
                lastMileTravel: 4.300000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.0",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "317848",
            name: "Hotel chola",
            uuid: "f61fc593-2701-4872-ad96-b6da7ff25041",
            city: "14",
            area: "Peelamedu",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "dqyowfw1xjihry4ikkli",
            cuisines: ["Indian"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 17,
            minDeliveryTime: 17,
            maxDeliveryTime: 17,
            slaString: "17 MINS",
            lastMileTravel: 0.699999988079071,
            slugs: {
                restaurant: "hotel-chola-ramanathapuram-ramanathapuram",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "NO 113, SOWRIPALAYAM BUS STOP BACK SIDE, SOWRIPALAYAM, COIMBATORE, Coimbatore Corporation Ward-56, Coimbatore, Tamil Nadu, 641028",
            locality: "Sowripalayam Road",
            parentId: 4714,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.6 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "317848",
                deliveryTime: 17,
                minDeliveryTime: 17,
                maxDeliveryTime: 17,
                lastMileTravel: 0.699999988079071,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.7",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "66268",
            name: "Hotel Sri Madurai Meenakshi",
            uuid: "ec218f70-3e45-4e2f-ac9c-a58bfc735018",
            city: "14",
            area: "Peelamedu",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "kohng6fk7log2eslepxc",
            cuisines: ["Biryani", "Chinese", "South Indian", "Chettinad"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 22,
            minDeliveryTime: 22,
            maxDeliveryTime: 22,
            slaString: "22 MINS",
            lastMileTravel: 1.5,
            slugs: {
                restaurant: "hotel-sri-madurai-meenakshi-vk-road-peelamedu",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "17/18. VK Road, Near PSG Tech Signal , Peelamedu, Cbe -04",
            locality: "Vk Road",
            parentId: 102648,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1.5 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "66268",
                deliveryTime: 22,
                minDeliveryTime: 22,
                maxDeliveryTime: 22,
                lastMileTravel: 1.5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.2",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "425423",
            name: "CakeZone",
            uuid: "fbef4a5b-77a1-412d-bb1d-97fe143a4fd8",
            city: "14",
            area: "Kamarajar Road, Singanallur",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "a6b6cf549e01de61b9c415e936ff4511",
            cuisines: ["Bakery", "Desserts", "Sweets", "Ice Cream"],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 28,
            minDeliveryTime: 28,
            maxDeliveryTime: 28,
            slaString: "28 MINS",
            lastMileTravel: 3,
            slugs: {
                restaurant: "cakezone-hopes-hopes",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "No.370, 1st Floor, Kamarajar Road, opp N.G.R School, Upplipalayam Po., Coimbatore Corporation ward -57, Coimbatore, Tamil Nadu - 641015",
            locality: "Kamarajar Road, Singanallur",
            parentId: 7003,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 2400,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 2400,
                message: "",
                title: "Delivery Charge",
                amount: "2400",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=7117133~p=4~eid=00000188-c901-79a5-0ed3-63e600d30427",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "425423",
                deliveryTime: 28,
                minDeliveryTime: 28,
                maxDeliveryTime: 28,
                lastMileTravel: 3,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.1",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "50793",
            name: "KFC",
            uuid: "123ce914-ea01-4386-a3df-a1d6e1b0094c",
            city: "14",
            area: "Peelamedu",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
            cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
            tags: [],
            costForTwo: 50000,
            costForTwoString: "₹500 FOR TWO",
            deliveryTime: 19,
            minDeliveryTime: 19,
            maxDeliveryTime: 19,
            slaString: "19 MINS",
            lastMileTravel: 2,
            slugs: {
                restaurant: "kfc-peelamedu-peelamedu",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "KFC, No.1258-1260, Avinashi Rd, Near Sri Ramakrishna Dental College and Hospital, Peelamedu, Coimbatore, Tamil Nadu 641004",
            locality: "Avinashi Road",
            parentId: 547,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2 kms",
            hasSurge: false,
            sla: {
                restaurantId: "50793",
                deliveryTime: 19,
                minDeliveryTime: 19,
                maxDeliveryTime: 19,
                lastMileTravel: 2,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "299600",
            name: "Fruit N Chaat",
            uuid: "5175ab9a-3c85-4ed1-bc15-b8a7debeb019",
            city: "14",
            area: "Peelamedu",
            totalRatingsString: "20+ ratings",
            cloudinaryImageId: "m42lw7qrm9uxlsh5myku",
            cuisines: ["Chaat", "Juices"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 27,
            minDeliveryTime: 27,
            maxDeliveryTime: 27,
            slaString: "27 MINS",
            lastMileTravel: 0.800000011920929,
            slugs: {
                restaurant: "fruit-n-chaat-race-course-race-course",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "NO 20, NAVA INDIA ROAD, NEAR HINDUSTAN COLLEGE, SOWRIPALAYAM POST, COIMBATORE, District - Coimbatore, STATE - Tamil Nadu",
            locality: "Nava India Road",
            parentId: 84734,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "299600",
                deliveryTime: 27,
                minDeliveryTime: 27,
                maxDeliveryTime: 27,
                lastMileTravel: 0.800000011920929,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 20,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "60958",
            name: "Denmarrk Drive-Inn Restaurant",
            uuid: "a05bd383-1620-4f2a-bea1-e37780295a5a",
            city: "14",
            area: "Ganapathy",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "kotlytcyvkm5c5sl86mk",
            cuisines: [
                "Tandoor",
                "North Indian",
                "Chinese",
                "Kebabs",
                "Juices",
                "Arabian",
            ],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            slaString: "29 MINS",
            lastMileTravel: 5,
            slugs: {
                restaurant:
                    "denmarrk-drive-inn-restaurant-ganapathy-coi_ganapathy",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "172/1, Marutham Complex, Sathy Road, Ganapathy, Coimbatore",
            locality: "Sathy Road",
            parentId: 4907,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 4100,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 4100,
                message: "",
                title: "Delivery Charge",
                amount: "4100",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=6964890~p=10~eid=00000188-c901-79a5-0ed3-63e800d30a62",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "5 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "30% OFF",
                subHeader: "UPTO ₹75",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "60958",
                deliveryTime: 29,
                minDeliveryTime: 29,
                maxDeliveryTime: 29,
                lastMileTravel: 5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.1",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "575570",
            name: "Nagerkovil Arya Bhavan",
            uuid: "478a4c15-86c4-44ed-9646-df9189dfd601",
            city: "14",
            area: "Peelamedu",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "yj6g7wugbi5qbvjtoqmr",
            cuisines: ["South Indian", "Chinese"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            slaString: "23 MINS",
            lastMileTravel: 2.0999999046325684,
            slugs: {
                restaurant:
                    "nagercoil-catering-private-limited(nagerkovil-ary-peelamedu-peelamedu",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "No:751, AVINASHI ROAD, NEAR SUGUNA KALYANA MANDAPAM,PEELAMEDU,COIMBATORE-641004 , Coimbatore Corporation Ward-39, Coimbatore, Tamil Nadu-641004",
            locality: "Avinash Road",
            parentId: 353249,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹199",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "575570",
                deliveryTime: 23,
                minDeliveryTime: 23,
                maxDeliveryTime: 23,
                lastMileTravel: 2.0999999046325684,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.4",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "53332",
            name: "Shree Aksshayam",
            uuid: "286eb1eb-0b33-49d0-a63e-5a2295999d80",
            city: "14",
            area: "Peelamedu",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "jhkqrufhwa0xsds1wqt8",
            cuisines: ["South Indian", "Chinese", "North Indian"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            slaString: "23 MINS",
            lastMileTravel: 1.7999999523162842,
            slugs: {
                restaurant: "shree-aksshayam-peelamedu-peelamedu",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "27-A, SNR College Road, Near Nava India Signal, Peelamedu, Coimbatore",
            locality: "Nava India Road",
            parentId: 7115,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1.7 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "53332",
                deliveryTime: 23,
                minDeliveryTime: 23,
                maxDeliveryTime: 23,
                lastMileTravel: 1.7999999523162842,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.2",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "230733",
            name: "Dairy House",
            uuid: "e5f1c8da-7063-4db1-b6ae-47be973e5e7e",
            city: "14",
            area: "Ramanathapuram",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "sjrklybrm5tmxvzoiqib",
            cuisines: ["Ice Cream"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 22,
            minDeliveryTime: 22,
            maxDeliveryTime: 22,
            slaString: "22 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
                restaurant: "dairy-house-peelamedu-peelamedu",
                city: "coimbatore",
            },
            cityState: "14",
            address: "NO25, CHINNA AYYAVU LAYOUT,OPP ADWAITH, GNS SCHOOL",
            locality: "Chinna Ayyavu Thevar Layout",
            parentId: 68048,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "15% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "230733",
                deliveryTime: 22,
                minDeliveryTime: 22,
                maxDeliveryTime: 22,
                lastMileTravel: 0.8999999761581421,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 100,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "141396",
            name: "Shahi Grill",
            uuid: "8bee0284-063f-4118-82ea-4b4d2de51ce9",
            city: "14",
            area: "Peelamedu",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "ivk9dv4nv9uus2j9rdsn",
            cuisines: [
                "Grill",
                "Biryani",
                "Tandoor",
                "Arabian",
                "South Indian",
                "Beverages",
            ],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 20,
            minDeliveryTime: 20,
            maxDeliveryTime: 20,
            slaString: "20 MINS",
            lastMileTravel: 1.899999976158142,
            slugs: {
                restaurant: "shahi-grill-peelamedu-peelamedu",
                city: "coimbatore",
            },
            cityState: "14",
            address: "661, Devaraj Complex, Avinashi Rd, Peelamedu, Coimbatore",
            locality: "Avinashi Road",
            parentId: 13253,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "141396",
                deliveryTime: 20,
                minDeliveryTime: 20,
                maxDeliveryTime: 20,
                lastMileTravel: 1.899999976158142,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "67645",
            name: "Night Lion by Madhampatty Pakashala",
            uuid: "372098e0-4c40-40ca-9ec4-f363863e1f17",
            city: "14",
            area: "Peelamedu",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "qgck9fzi17ljdvwboljb",
            cuisines: ["North Indian", "South Indian", "Chinese", "Haleem"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 27,
            minDeliveryTime: 27,
            maxDeliveryTime: 27,
            slaString: "27 MINS",
            lastMileTravel: 3.9000000953674316,
            slugs: {
                restaurant: "fireflies-night-restaurant-peelamedu-peelamedu",
                city: "coimbatore",
            },
            cityState: "14",
            address: "Nehru street, Avinashi road, Peelamedu, Coimbatore",
            locality: "Gauthama Puri Nagar",
            parentId: 377170,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 2400,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 2400,
                message: "",
                title: "Delivery Charge",
                amount: "2400",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=6964837~p=13~eid=00000188-c901-79a5-0ed3-63e900d30d2f",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3.9 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "67645",
                deliveryTime: 27,
                minDeliveryTime: 27,
                maxDeliveryTime: 27,
                lastMileTravel: 3.9000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "3.9",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "56506",
            name: "McDonald's",
            uuid: "1303381b-3f16-4663-926e-0ac9568874dd",
            city: "14",
            area: "Avinashi Road",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "ee5f8e06b300efc07c9fe3f4df40dfc4",
            cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 19,
            minDeliveryTime: 19,
            maxDeliveryTime: 19,
            slaString: "19 MINS",
            lastMileTravel: 2.5999999046325684,
            slugs: {
                restaurant: "mcdonalds-brookefields-fc-peelamedu",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "Hardcastle Restaurants Pvt Ltd,McDonalds Family Restaurants Pvt Ltd,Restaurant No. 1,Ground Floor and Upper Ground Fr,Village sowipalayam,Peelamedu Avinashi Road,Coimbatore 641014",
            locality: "Fun Republic Mall",
            parentId: 630,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.5 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "FREE ITEM",
                subHeader: "",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "56506",
                deliveryTime: 19,
                minDeliveryTime: 19,
                maxDeliveryTime: 19,
                lastMileTravel: 2.5999999046325684,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.2",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "52500",
            name: "Burger Ka Baap",
            uuid: "13046467-2a18-482a-a374-9dc16458a95c",
            city: "14",
            area: "PSG Peelamedu",
            totalRatingsString: "5000+ ratings",
            cloudinaryImageId: "a3fywprqg3svnp2nied7",
            cuisines: ["Beverages"],
            tags: [],
            costForTwo: 50000,
            costForTwoString: "₹500 FOR TWO",
            deliveryTime: 25,
            minDeliveryTime: 25,
            maxDeliveryTime: 25,
            slaString: "25 MINS",
            lastMileTravel: 1.399999976158142,
            slugs: {
                restaurant: "burger-ka-baap-peelamedu-peelamedu",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "Avinashi Road, Near PSG College Of Technology, Peelamedu, Coimbatore",
            locality: "Avinashi Road",
            parentId: 21754,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1.3 kms",
            hasSurge: false,
            sla: {
                restaurantId: "52500",
                deliveryTime: 25,
                minDeliveryTime: 25,
                maxDeliveryTime: 25,
                lastMileTravel: 1.399999976158142,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 5000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "570531",
            name: "Pongalur Sri Annapoornis Sweets",
            uuid: "7baf49f2-7eb1-4335-9a7e-14a39c03a151",
            city: "14",
            area: "Peelamedu",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "u7dpfty6qilyux9z5ore",
            cuisines: ["Sweets", "Snacks"],
            tags: [],
            costForTwo: 15000,
            costForTwoString: "₹150 FOR TWO",
            deliveryTime: 14,
            minDeliveryTime: 14,
            maxDeliveryTime: 14,
            slaString: "14 MINS",
            lastMileTravel: 1.5,
            slugs: {
                restaurant:
                    "pongalur-sri-annapoornis-sweets-peelamedu-peelamedu-2",
                city: "coimbatore",
            },
            cityState: "14",
            address:
                "436 D, Avinashi Rd, Peelamedu, Masakalipalayam, Coimbatore, Tamil Nadu 641004, India",
            locality: "Avinashi Road",
            parentId: 11250,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1.5 kms",
            hasSurge: false,
            sla: {
                restaurantId: "570531",
                deliveryTime: 14,
                minDeliveryTime: 14,
                maxDeliveryTime: 14,
                lastMileTravel: 1.5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.4",
            totalRatings: 100,
            new: false,
        },
        subtype: "basic",
    },
];

export default resList;
